theme = "kanagawa-dragon"
confirm-before-quit = false
padding-y = [12, 0]
padding-x = 15

[cursor]
shape = 'beam'

[fonts]
size = 20
family = "CaskaydiaCove Nerd Font"

[window]
blur = true
opacity = 0.8

[editor]
program = "nvim"

[shell]
program = "tmux"
