#!/bin/bash
set -euo pipefail

if command -v zsh >/dev/null; then
  sudo chsh -s $(command -v zsh) $USER
fi

if [ ! -d "$HOME/.zsh" ]; then
  mkdir -p "$HOME/.zsh"
fi

curl -s https://ohmyposh.dev/install.sh | bash -s -- -d "$HOME/.local/bin"

if ! command -v chezmoi >/dev/null; then
  sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply git@github.com:jameskaupert/dotfiles.git
fi

exit 0
