#!/bin/bash
set -euo pipefail

XDG_CONFIG_HOME="$HOME/.config"

echo "-- changing user shell to zsh --"
if command -v zsh >/dev/null; then
  sudo chsh -s $(command -v zsh) $USER
fi

echo "-- installing chezmoi -- "
# chezmoi install
if ! command -v chezmoi >/dev/null; then
  sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply git@github.com:jameskaupert/dotfiles-functional.git
fi

if [ ! -d "$HOME/.zsh" ]; then
  mkdir -p "$HOME/.zsh"
fi

echo "-- installing oh-my-posh --"
# oh-my-posh install
curl -s https://ohmyposh.dev/install.sh | bash -s

echo "-- installing zoxide --"
# zoxide install
curl -sSfL https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | sh

exit 0
