import = ["~\\AppData\\Roaming\\alacritty\\themes\\themes\\catppuccin-macchiato.toml"]

[font]
size = 16

[font.normal]
family = "ZedMono Nerd Font Mono"
style = "Regular"

[font.bold]
family = "ZedMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "ZedMono Nerd Font Mono"
style = "Italic"

[font.bold_italic]
family = "ZedMono Nerd Font Mono"
style = "Bold Italic"

[mouse]
hide_when_typing = true

[shell]
program="C:\\Windows\\System32\\wsl.exe ~"

[window]
decorations = "none"

[window.padding]
x = 7
y = 10
ty/catppuccin-macchiato.toml"







