[tools]
usage = "latest" # mise completion
bat = "latest"
chezmoi = "latest"
fd = "latest"
fzf = "latest"
eza = "latest"
ripgrep = "latest"
jq = "latest"
neovim = "latest"
node = "latest"
python = "latest"
kubectl = "latest"
