vim.g.mapleader = " "
vim.keymap.set("n", "<leader>pv", vim.cmd.Ex)
vim.keymap.set("n", "<leader><leader>", function()
    vim.cmd("so")
end)
vim.keymap.set("n", "<leader>wa", function()
    vim.cmd("wa")
end)
vim.keymap.set("n", "<leader>ff", function()
    vim.cmd("LspZeroFormat")
end)
vim.keymap.set("n", "<leader>gt", "<cmd>!go test<CR>")
vim.keymap.set("i", "kj", "<Esc>")
vim.keymap.set("v", "<leader>p", [["_dP]])
vim.keymap.set("v", "<leader>y", [["+y]])
vim.keymap.set("v", "J", ":m '>+1<CR>gv=gv")
vim.keymap.set("v", "K", ":m '<-2<CR>gv=gv")
